### ISSUE TITLE
Java.sql.Timestamp

### ISSUE THREAD

**Issue by Darthscion55** [Weathercold/extra-logging#3] opened 2023-12-09 23:42 UTC
As others have said, i am unable to download this mod. 
![Mindustry_6O5bJXiNXQ](https://github.com/Weathercold/extra-logging/assets/140124893/b62b2a63-996e-461e-b373-16d3a419e95e)
![Mindustry_V93G6lYmRX](https://github.com/Weathercold/extra-logging/assets/140124893/07a68211-456c-4f95-8740-a6b52cec53fa)

Each attempt to download creates a new ZIP file in the mods folder. 
here is my currently installed Mods. 
![Mindustry_lMI0IoFNmZ](https://github.com/Weathercold/extra-logging/assets/140124893/5bc07f59-4f84-46b2-9eeb-2c1e278d8912)

It acts like its downloaded, but then on restarting the game, the mod simply is gone. What is even more weird, is I had this downloaded at one point..

**Comment by Weathercold** [comment] 2023-12-10 01:06
Do you use the steam version? I was able to reproduce this error with the steam version and I think I understand the cause. I can try to fix it.

**Comment by Darthscion55** [comment] 2023-12-10 07:56
> Do you use the steam version? I was able to reproduce this error with the steam version and I think I understand the cause. I can try to fix it.

Yes I do use the steam version.
Note: I do have foos client installed and did not test (from what I remember) without it installed. 

I also get errors while trying to install it on mobile too. Samsung Galaxy S22. Android 14. 
![Screenshot_20231210_004858_Mindustry](https://github.com/Weathercold/extra-logging/assets/140124893/64f8e997-3a3f-4b60-ad35-41926bc376c9)
![Screenshot_20231210_004918_Mindustry](https://github.com/Weathercold/extra-logging/assets/140124893/9fc86dc6-f2f6-4591-a3b1-c02cafb05a6e)
![Screenshot_20231210_004926_Mindustry](https://github.com/Weathercold/extra-logging/assets/140124893/d268a829-0dbc-404a-a365-838ae6cb28ef)
![Screenshot_20231210_004936_Mindustry](https://github.com/Weathercold/extra-logging/assets/140124893/fc623340-a93e-4ca5-986c-0a862d6783ec)
![Screenshot_20231210_004944_Mindustry](https://github.com/Weathercold/extra-logging/assets/140124893/5cd07000-4a52-4d88-ab0a-3bf1a1c4c812)
![Screenshot_20231210_004949_Mindustry](https://github.com/Weathercold/extra-logging/assets/140124893/ebd6c22b-4715-49c8-bfbc-e45ba1b69601)
![Screenshot_20231210_004953_Mindustry](https://github.com/Weathercold/extra-logging/assets/140124893/b631af1e-6355-449a-966e-13f033058659)

**Comment by Darthscion55** [comment] 2023-12-10 07:57
Oops sorry, clicked wrong button XD

**Comment by Darthscion55** [comment] 2023-12-10 08:00
> I can try to fix it.

I would LOVE that. Thank you!

**Comment by Weathercold** [comment] 2023-12-10 09:04
I managed to fix the error by simply switching to newer version of clojure. Sadly however, the fix may require me to sacrifice Android support (though I don't want to stay on an outdated version of clojure, and some features don't work on Android anyway).

**Comment by Weathercold** [comment] 2023-12-10 10:24
Should be fixed now

**Closed as completed** 2023-12-10 10:23 UTC

**Comment by buthed010203** [comment] 2023-12-11 22:24
He jinxed it
![image](https://github.com/Weathercold/extra-logging/assets/26940575/3a9ef371-a357-4d0f-8d03-c12633603e05)
